CREATE TABLE `personality` (
  `id` int(11) NOT NULL  AUTO_INCREMENT ,
  `PERSON_NAME` varchar(45) NOT NULL,
  `PERSON_SEX` varchar(10) NOT NULL,
  `PERSON_DOB` date NOT NULL,
  `PERSON_DOE` date DEFAULT NULL,
  `PERSON_ABOUT` varchar(4000) DEFAULT NULL,
  `PERSON_PIC` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;