CREATE TABLE `eduproject`.`personality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PERSON_NAME` VARCHAR(45) NOT NULL ,
  `PERSON_AGE` INT NOT NULL,
  `PERSON_DOB` DATE NOT NULL,
  `PERSON_ALIVE` VARCHAR(45) NOT NULL,
  `PERSON_DOD` DATE NULL,
  `PERSON_ABOUT` VARCHAR(4000) NULL,
  `PERSON_PIC` BLOB NULL,
  PRIMARY KEY (`id`));
