CREATE TABLE `QUESTION_ANS` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `QUESTION` varchar(1000) DEFAULT NULL,
  `OPTION_A` varchar(1000) DEFAULT NULL,
  `OPTION_B` varchar(1000) DEFAULT NULL,
  `OPTION_C` varchar(1000) DEFAULT NULL,
  `OPTION_D` varchar(1000) DEFAULT NULL,
  `QTYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
);

